version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: microsservicos-db
    environment:
      POSTGRES_DB: testefinal_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  logs-service:
    build: ./logs-service
    container_name: logs-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: testefinal_db
      PORT: 8084
      CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testefinal_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  events-service:
    build: ./events-service
    container_name: events-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testefinal_db?currentSchema=events_schema
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      PORT: 8082
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_SECURE: "false"
      SMTP_USER: pedroportzdorneles@gmail.com
      SMTP_PASS: vqdvysiohpllbplu
      EMAIL_FROM: noreply@gmail.com
      LOGS_API_URL: http://logs-service:8084/logs
      CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "8082:8082"
    depends_on:
      logs-service:
        condition: service_started

  certificate-service:
    build: ./certificate-service
    container_name: certificate-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: testefinal_db
      PORT: 8083
      LOGS_API_URL: http://logs-service:8084/logs
      CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      logs-service:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_USER_API_URL: http://177.44.248.107:8080/api
        NEXT_PUBLIC_EVENTS_API_URL: http://177.44.248.107:8081/api
        NEXT_PUBLIC_NOTIFICATION_API_URL: http://177.44.248.107:8082/api
        NEXT_PUBLIC_CERTIFICATE_API_URL: http://177.44.248.107:8083/certificates
        NEXT_PUBLIC_CERTIFICATE_API_BASE_URL: http://177.44.248.107:8083
        NEXT_PUBLIC_LOGS_API_URL: http://177.44.248.107:8084
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - events-service
      - notification-service
      - certificate-service

volumes:
  postgres_data:
